version: '3.8'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb11
    ports:
    - 27017:27017
    volumes:
    - ./data
  flask-service:
    image: flask_image
    restart: always
    container_name: flask11
    depends_on:
      - mongodb
    ports:
      - 5000:5000
    environment:
      - MONGODB_HOST=mongodb"